### ISSUE TITLE
Seeking Assistance on Dataset Issues for CLIP-Driven Model Reproduction

### ISSUE THREAD

**Issue by itsnotacie** [skapoor2024/RAID-5_SAN#1]
Hi, I am also working on reproducing the paper CLIP-Driven Universal Model for Organ Segmentation and Tumor Detection. I’m currently facing some issues with the dataset part. May I discuss them with you? Could you please provide an email or WeChat contact?

**Comment by skapoor2024** [comment]
Hi you can reach out to me on s.kapoor@ufl.edu
